# Usar la imagen base ligera de Nginx
FROM nginx:alpine

# Copiar la página web al directorio predeterminado de Nginx
COPY ./app/index.html /usr/share/nginx/html/index.html

# Exponer el puerto 80 para el acceso HTTP
EXPOSE 80
