name: Terraform File Scan

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'infra/Terraform/**'

env:
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
  TFLINT_VERSION: "v0.50.0"

jobs:
  terraform-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.9.0"

      - name: Terraform Format Check
        working-directory: ./infra/Terraform
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ./infra/Terraform
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: Initialize TFLint
        working-directory: ./infra/Terraform
        run: tflint --init

      - name: Run TFLint
        working-directory: ./infra/Terraform
        run: tflint --format compact
        
