name: Test AWS Connection

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Verificar identidad con AWS CLI
        run: aws sts get-caller-identity

      - name: Listar buckets S3 (prueba)
        run: aws s3 ls
